[mgr]


keymap = [
	{ on = "<Esc>", run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },
	{ on = "q",     run = "quit",               desc = "Quit" },
	{ on = "<C-d>",     run = "quit --no-cwd-file", desc = "Quit w/o cwd" },
	{ on = "w",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },

	# Hopping
	{ on = "k", run = "arrow prev", desc = "Previous file" },
	{ on = "j", run = "arrow next", desc = "Next file" },
	{ on = "<Up>",   run = "arrow prev", desc = "Previous file" },
	{ on = "<Down>", run = "arrow next", desc = "Next file" },

	{ on = "<PageUp>",   run = "arrow -50%",  desc = "Move cursor up half page" },
	{ on = "<PageDown>", run = "arrow 50%",   desc = "Move cursor down half page" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "Go to top" },
	{ on = "G",          run = "arrow bot", desc = "Go to bottom" },

	# Navigation
	{ on = "h", run = "leave", desc = "Back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },
	{ on = "<Left>",  run = "leave", desc = "Back to the parent directory" },
	{ on = "<Right>", run = "enter", desc = "Enter the child directory" },
	{ on = "<Enter>", run = "enter", desc = "Enter the child directory" },

	{ on = ["g","p"], run = "back",    desc = "Back to previous directory" },
	{ on = ["g","n"], run = "forward", desc = "Forward to next directory" },

	# Toggle
	{ on = "<Space>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = "A",   run = "toggle_all --state=on", desc = "Select all files" },

	# Visual mode
	{ on = "v", run = "visual_mode",         desc = "Enter visual mode (selection mode)" },

	# Seeking
	{ on = "K", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "J", run = "seek 5",  desc = "Seek down 5 units in the preview" },
	{ on = "<S-PageUp>", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "<S-PageDown>", run = "seek 5",  desc = "Seek down 5 units in the preview" },

	# Spotting
	{ on = [":","?"], run = "spot", desc = "Spot file" },

	# Operation
	#{ on = ["e","e"],         run = "open",                        desc = "Open" },
	#{ on = ["e","m"],         run = "open --interactive",          desc = "Open menu" },
	{ on = "e",         run = "open --interactive",          desc = "Open menu" },
	{ on = ["y","y"],   run = "yank",                        desc = "Copy" },
	{ on = ["y","x"],   run = "yank --cut",                  desc = "Cut" },
	{ on = "x",         run = "yank --cut",                  desc = "Yank selected files (cut)" },
	{ on = "p",         run = "paste",                       desc = "Paste yanked files" },
	{ on = "P",         run = "paste --force",               desc = "Paste yanked files (overwrite if the destination exists)" },
	{ on = ["y","Y"],         run = "unyank",                      desc = "Cancel" },
	{ on = "d",         run = "remove",                      desc = "Trash selected files" },
	{ on = "a",         run = "create",                      desc = "Create a file (ends with / for directories)" },
	{ on = "c",         run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
	{ on = ".",         run = "hidden toggle",               desc = "Toggle the visibility of hidden files" },
	{ on = ["s","f"],   run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = ["s","g"],   run = "search --via=rg",             desc = "Search files by content via ripgrep" },
	{ on = ["s","<Esc>"],run = "escape --search",             desc = "Cancel the ongoing search" },
	{ on = "z",         run = "plugin zoxide",               desc = "Jump to a directory via zoxide" },
	{ on = "Z",         run = "plugin fzf",                  desc = "Jump to a file/directory via fzf" },


	# Linemode
	{ on = [ ";", "s" ], run = "linemode size",        desc = "size" },
	{ on = [ ";", "p" ], run = "linemode permissions", desc = "permissions" },
	{ on = [ ";", "b" ], run = "linemode btime",       desc = "btime" },
	{ on = [ ";", "m" ], run = "linemode mtime",       desc = "mtime" },
	{ on = [ ";", "o" ], run = "linemode owner",       desc = "owner" },
	{ on = [ ";", "n" ], run = "linemode none",        desc = "none" },

	# Copy
	{ on = [ "y", "c" ], run = "copy path",             desc = "File path" },
	{ on = [ "y", "d" ], run = "copy dirname",          desc = "Dir path" },
	{ on = [ "y", "f" ], run = "copy filename",         desc = "Filename" },
	{ on = [ "y", "n" ], run = "copy name_without_ext", desc = "Filename wo ext" },

	# Filter
	{ on = "f", run = "filter --smart", desc = "Filter files" },

	# Find
	{ on = "/", run = "find --smart",            desc = "Find next file" },
	{ on = "n", run = "find_arrow",              desc = "Next found" },
	{ on = "N", run = "find_arrow --previous",   desc = "Previous found" },

	# Sorting
	{ on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ],  desc = "Modified asc" },
	{ on = "<F1>", run = "help", desc = "Open help" },
	{ on = [ ",", "M" ], run = [ "sort mtime --reverse=yes", "linemode mtime" ], desc = "Modified dsc" },
	{ on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime" ],  desc = "Created asc" },
	{ on = [ ",", "B" ], run = [ "sort btime --reverse=yes", "linemode btime" ], desc = "Created dsc" },
	{ on = [ ",", "e" ], run = "sort extension --reverse=no",                    desc = "Extension asc" },
	{ on = [ ",", "E" ], run = "sort extension --reverse=yes",                   desc = "Extension dsc" },
	{ on = [ ",", "a" ], run = "sort alphabetical --reverse=no",                 desc = "Name asc" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse=yes",                desc = "Name dsc" },
	{ on = [ ",", "n" ], run = "sort natural --reverse=no",                      desc = "Naturally" },
	{ on = [ ",", "N" ], run = "sort natural --reverse=yes",                     desc = "Naturally (reverse)" },
	{ on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size" ],    desc = "Size asc" },
	{ on = [ ",", "S" ], run = [ "sort size --reverse=yes", "linemode size" ],   desc = "Size dsc" },

	# Goto
	{ on = [ "g", "h" ],       run = "cd ~",             desc = "Go home" },
	{ on = [ "g", "j" ], run = "cd --interactive", desc = "Jump interactively" },
	{ on = [ "g", "f" ],       run = "follow",           desc = "Follow symlink" },

	# Tabs
	{ on = "t", run = "tab_create --current", desc = "Create a new tab with CWD" },

	{ on = "[", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
	{ on = "]", run = "tab_switch 1 --relative",  desc = "Switch to next tab" },

	# Tasks
	{ on = [":","/"], run = "tasks:show", desc = "Show task manager" },

	# Help
	{ on = "?",    run = "help", desc = "Open help" },

	{ on = "<Tab>",    run = "peek", desc = "Toggle preview" },
	{ on = [":",";"],         run = "shell --interactive",         desc = "Run a shell command" },
	{ on = [":",":"],         run = "shell /bin/zsh --block", desc = "zsh" },

	{ on = [":","d"], run = "shell -- dragon -x -i -T %s1", desc = "Dragon" }
]


[tasks]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "q",     run = "close",               desc = "Close" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },
]
[spot]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "w",     run = "close",              desc = "Close the current tab, or quit if it's last" },
]
[pick]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "w",     run = "close",              desc = "Close the current tab, or quit if it's last" },
]
[input]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "w",     run = "close",              desc = "Close the current tab, or quit if it's last" },
]
[confirm]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "w",     run = "close",              desc = "Close the current tab, or quit if it's last" },
]
[cmp]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "w",     run = "close",              desc = "Close the current tab, or quit if it's last" },
]
[help]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "<C-c>",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "w",     run = "close",              desc = "Close the current tab, or quit if it's last" },
]
